RestorantMVC/Models/LayoutViewModel.cs
using Entites.Concrate;

namespace RestorantMVC.Models
{
    public class LayoutViewModel
    {
        public ICollection<Kategori> Kategoriler { get; set; }
    }
}

RestorantMVC/Areas/Admin/Controllers/UrunController.cs
using AutoMapper;
using DAL.Contexts;
using Entites.Concrate;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using RestorantMVC.Extensions;
using RestorantMVC.Models;
using System.Formats.Tar;
using System.IO.MemoryMappedFiles;

namespace RestorantMVC.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize]
    public class UrunController : Controller
    {
        private readonly SqlDbContext dbContext;
        private readonly IMapper mapper;
        private readonly IWebHostEnvironment hostingEnviroment;
        private readonly UserManager<Firma> userManager;
        private string firmaId;


        public UrunController(SqlDbContext context, UserManager<Firma> userManager, IMapper Mapper, IWebHostEnvironment _hostingEnviroment)
        {
            dbContext = context;
            this.userManager = userManager;
            mapper = Mapper;
            hostingEnviroment = _hostingEnviroment;
        }

        // GET: Admin/Urun
        public async Task<IActionResult> Index()
        {
            await this.SetUser(userManager);
            firmaId = userManager.GetUserId(User);

            var sqlDbContext = dbContext.Urunler.FirmaFilter(firmaId).Include(u => u.Kategori);

            return View(await sqlDbContext.ToListAsync());
        }

        // GET: Admin/Urun/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            await this.SetUser(userManager);

            if (id == null || dbContext.Urunler == null)

            {
                return NotFound();
            }

            var urun = await dbContext.Urunler
                .Include(u => u.Kategori)
                .FirstOrDefaultAsync(m => m.ID == id);
            if (urun == null)
            {
                return NotFound();
            }

            return View(urun);
        }

        // GET: Admin/Urun/Create
        public async Task<IActionResult> Create()
        {
            await this.SetUser(userManager);
            firmaId = userManager.GetUserId(User);

            ViewData["KategoriID"] = new SelectList(dbContext.Kategoriler.FirmaFilter(firmaId) , "ID" , "KategoriAdi");;

            return View();
        }

        // POST: Admin/Urun/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("UrunAdi,UrunAciklama,FotografLink,Fiyat,KategoriID,ID,CreateTime,UpdateTime")] UrunModelDTO urunV)
        {
            await this.SetUser(userManager);
            firmaId = userManager.GetUserId(User);

            var urun = mapper.Map<Urun>(urunV);

            urun.FirmaId = firmaId;
            urun.CreateTime = DateTime.Now;
            // Resim Yükleme Alanı.


            if (!IsUniqueForFirma(urun.UrunAdi , firmaId))
            {
                ModelState.AddModelError("KategoriAdi" , "Kategori adı zaten mevcut");
                return View(urun);
            }
            if (!ModelState.IsValid)
            {
                try
                {
                    dbContext.Urunler.Add(urun);
                    await dbContext.SaveChangesAsync();
                    return RedirectToAction("Index");
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError("" , "Aynı İsimde bir ürün zaten mevcut");
                    ViewData["KategoriID"] = new SelectList(dbContext.Kategoriler.FirmaFilter(firmaId) , "ID" , "KategoriAdi");
                    return Json(ex);
                }
            }
            return View(urun);
        }

        private bool IsUniqueForFirma(string urunadi , string firmaId)
        {
            firmaId = userManager.GetUserId(User);

            var kategorivarmi = dbContext.Urunler.FirstOrDefault(c => c.UrunAdi == urunadi && c.FirmaId == firmaId);
            return kategorivarmi == null;
        }

        // GET: Admin/Urun/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            await this.SetUser(userManager);
            firmaId = userManager.GetUserId(User);

            var urun = dbContext.Urunler.Find(id);
            ViewData["KategoriID"] = new SelectList(dbContext.Kategoriler.FirmaFilter(firmaId).ToList() , "ID" , "KategoriAdi");

            return View(urun);
        }

        // POST: Admin/Urun/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id , [Bind("UrunAdi,UrunAciklama,FotografLink,Fiyat,KategoriID,ID,CreateTime,UpdateTime")] Urun urun)
        {
            await this.SetUser(userManager);
            firmaId = userManager.GetUserId(User);
            urun.FirmaId = firmaId;
            urun.UpdateTime = DateTime.Now;

            if (id != urun.ID)
            {
                return NotFound();
            }
            if (ModelState.IsValid)
            {
                return View(urun);
            }
            try
            {
                dbContext.Urunler.Update(urun);
                await dbContext.SaveChangesAsync();
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("" , ex.Message);
                ViewData["KategoriID"] = new SelectList(dbContext.Kategoriler.FirmaFilter(firmaId).ToList() , "ID" , "KategoriAdi");
                return View(urun);
            }
            return RedirectToAction("Index");
        }

        // GET: Admin/Urun/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            await this.SetUser(userManager);

            if (id == null || dbContext.Urunler == null)

            {
                return NotFound();
            }

            var urun = await dbContext.Urunler
                .Include(u => u.Kategori)
                .FirstOrDefaultAsync(m => m.ID == id);
            if (urun == null)
            {
                return NotFound();
            }

            return View(urun);
        }

        // POST: Admin/Urun/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            await this.SetUser(userManager);

            if (dbContext.Urunler == null)

            {
                return Problem("Entity set 'SqlDbContext.Urunler'  is null.");
            }
            var urun = await dbContext.Urunler.FindAsync(id);
            if (urun != null)
            {
                dbContext.Urunler.Remove(urun);
            }

            await dbContext.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool UrunExists(int id)
        {
            return (dbContext.Urunler?.Any(e => e.ID == id)).GetValueOrDefault();
        }
    }
}

RestorantMVC/Controllers/SiparisController.cs
using DAL.Contexts;
using Entites.Concrate;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace RestorantMVC.Controllers
{
    /// <summary>
    /// Sipariş işlemlerini yönetmek için kullanılan Controller sınıfı.
    /// </summary>
    public class SiparisController : Controller
    {
        private readonly SqlDbContext _context;

        public SiparisController(SqlDbContext context)
        {
            _context = context;
        }

        /// <summary>
        /// Siparişlerin listesini görüntülemek için kullanılan işlem.
        /// </summary>
        public async Task<IActionResult> Index()
        {
            //MasaID'nin siparişleri listelenir.
            int masaid = Convert.ToInt32(HttpContext.Request.Cookies["MasaId"]);
            var siparisMasterlar = _context.SiparisMasterlar.Where(s => s.MasaId == masaid);
            var siparisMaster = siparisMasterlar.FirstOrDefault();
            var siparisDetaylari = _context.SiparisDetaylar.Where(d => d.SiparisMasterId == siparisMaster.ID).ToList();

            // Urun'lerin isimleri null dönmesin diye ürünlerin atamasını DB'den atıyorum.
            foreach (var item in siparisDetaylari)
                if (item.Urun == null)
                    item.Urun = _context.Urunler.Find(item.UrunId);

            return View(siparisDetaylari);
        }

        /// <summary>
        /// Belirli bir siparişin detaylarını görüntülemek için kullanılan işlem.
        /// </summary>
        /// <param name="id">Sipariş detayının kimliği</param>
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.SiparisDetaylar == null)
            {
                return NotFound();
            }

            var siparisDetay = await _context.SiparisDetaylar
            .Include(s => s.SiparisMaster)
            .Include(s => s.Urun)
            .FirstOrDefaultAsync(m => m.ID == id);
            if (siparisDetay == null)
            {
                return NotFound();
            }

            return View(siparisDetay);
        }

        /// <summary>
        /// Yeni bir sipariş detayı oluşturmak için kullanılan işlem.
        /// </summary>
        public IActionResult Create()
        {
            ViewData["SiparisMasterId"] = new SelectList(_context.SiparisMasterlar , "ID" , "ID");
            ViewData["UrunId"] = new SelectList(_context.Urunler , "ID" , "UrunAciklama");
            return View();
        }

        /// <summary>
        /// Yeni bir sipariş detayı oluşturmak için kullanılan POST işlemi.
        /// </summary>
        /// <param name="siparisDetay">Oluşturulan sipariş detayı</param>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("SiparisMasterId,UrunId,Adet,Fiyat,ID,CreateTime,UpdateTime")] SiparisDetay siparisDetay)
        {
            if (ModelState.IsValid)
            {
                _context.Add(siparisDetay);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["SiparisMasterId"] = new SelectList(_context.SiparisMasterlar , "ID" , "ID" , siparisDetay.SiparisMasterId);
            ViewData["UrunId"] = new SelectList(_context.Urunler , "ID" , "UrunAciklama" , siparisDetay.UrunId);
            return View(siparisDetay);
        }

        /// <summary>
        /// Belirli bir sipariş detayını düzenlemek için kullanılan işlem.
        /// </summary>
        /// <param name="id">Düzenlenecek sipariş detayının kimliği</param>
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.SiparisDetaylar == null)
            {
                return NotFound();
            }

            var siparisDetay = await _context.SiparisDetaylar.FindAsync(id);
            if (siparisDetay == null)
            {
                return NotFound();
            }
            ViewData["SiparisMasterId"] = new SelectList(_context.SiparisMasterlar , "ID" , "ID" , siparisDetay.SiparisMasterId);
            ViewData["UrunId"] = new SelectList(_context.Urunler , "ID" , "UrunAciklama" , siparisDetay.UrunId);
            return View(siparisDetay);
        }

        /// <summary>
        /// Belirli bir sipariş detayını düzenlemek için kullanılan POST işlemi.
        /// </summary>
        /// <param name="id">Düzenlenecek sipariş detayının kimliği</param>
        /// <param name="siparisDetay">Düzenlenen sipariş detayı</param>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id , [Bind("SiparisMasterId,UrunId,Adet,Fiyat,ID,CreateTime,UpdateTime")] SiparisDetay siparisDetay)
        {
            if (id != siparisDetay.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(siparisDetay);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!SiparisDetayExists(siparisDetay.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["SiparisMasterId"] = new SelectList(_context.SiparisMasterlar , "ID" , "ID" , siparisDetay.SiparisMasterId);
            ViewData["UrunId"] = new SelectList(_context.Urunler , "ID" , "UrunAciklama" , siparisDetay.UrunId);
            return View(siparisDetay);
        }

        /// <summary>
        /// Belirli bir sipariş detayını silmek için kullanılan işlem.
        /// </summary>
        /// <param name="id">Silinecek sipariş detayının kimliği</param>
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.SiparisDetaylar == null)
            {
                return NotFound();
            }

            var siparisDetay = await _context.SiparisDetaylar
            .Include(s => s.SiparisMaster)
            .Include(s => s.Urun)
            .FirstOrDefaultAsync(m => m.ID == id);
            if (siparisDetay == null)
            {
                return NotFound();
            }

            return View(siparisDetay);
        }

        /// <summary>
        /// Belirli bir sipariş detayını silmek için kullanılan POST işlemi.
        /// </summary>
        /// <param name="id">Silinecek sipariş detayının kimliği</param>
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.SiparisDetaylar == null)
            {
                return Problem("Entity set 'SqlDbContext.SiparisDetaylar'  is null.");
            }
            var siparisDetay = await _context.SiparisDetaylar.FindAsync(id);
            if (siparisDetay != null)
            {
                _context.SiparisDetaylar.Remove(siparisDetay);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool SiparisDetayExists(int id)
        {
            return (_context.SiparisDetaylar?.Any(e => e.ID == id)).GetValueOrDefault();
        }
    }
}

RestorantMVC/Areas/Admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>@ViewData["Title"] - QRestorant</title>
    <!-- plugins:css -->
    <link rel="stylesheet" href="~/assets/vendors/mdi/css/materialdesignicons.min.css">
    <link rel="stylesheet" href="~/assets/vendors/css/vendor.bundle.base.css">
    <!-- endinject -->
    <!-- Plugin css for this page -->
    <link rel="stylesheet" href="~/assets/vendors/jvectormap/jquery-jvectormap.css">
    <link rel="stylesheet" href="~/assets/vendors/flag-icon-css/css/flag-icon.min.css">
    <link rel="stylesheet" href="~/assets/vendors/owl-carousel-2/owl.carousel.min.css">
    <link rel="stylesheet" href="~/assets/vendors/owl-carousel-2/owl.theme.default.min.css">
    <!-- End plugin css for this page -->
    <!-- inject:css -->
    <!-- endinject -->
    <!-- Layout styles -->
    <link rel="stylesheet" href="~/assets/css/style.css">
    <!-- End layout styles -->
    <link rel="shortcut icon" href="~/assets/images/favicon.png" />
</head>
<body>
    <div class="container-scroller">
        <!-- partial:partials/_sidebar.html -->
        <nav class="sidebar sidebar-offcanvas" id="sidebar">
            <div class="sidebar-brand-wrapper d-none d-lg-flex align-items-center justify-content-center fixed-top">
                <a class="sidebar-brand brand-logo"  ><img src="~/assets/images/logo.svg" alt="logo" /></a>
                <a class="sidebar-brand brand-logo-mini"  ><img src="~/assets/images/logo-mini.svg" alt="logo" /></a>
            </div>
            <ul class="nav">
                <li class="nav-item profile">
                    <div class="profile-desc">
                        <div class="profile-pic">
                            <div class="count-indicator">
                                <img class="img-xs rounded-circle " src="~/assets/images/faces/face15.jpg" alt="">
                                <span class="count bg-success"></span>
                            </div>
                            <div class="profile-name">
                                <h5 class="mb-0 font-weight-normal">@ViewBag.User.UserName</h5>
                            </div>
                        </div>
                    </div>
                </li>
                <li class="nav-item nav-category">
                    <span class="nav-link">Yönlendirmeler</span>
                </li>
                <li class="nav-item menu-items">
                </li>
                <li class="nav-item menu-items">
                    <a class="nav-link" asp-area="Admin" asp-controller="Kategori" asp-action="Index">
                        <span class="menu-icon">
                            <i class="mdi mdi-buffer"></i>
                        </span>
                        <span class="menu-title">Admin/Kategori</span>
                    </a>
                </li>
                <li class="nav-item menu-items">
                    <a class="nav-link" asp-area="Admin" asp-controller="Urun" asp-action="Index">
                        <span class="menu-icon">
                            <i class="mdi mdi-package-variant-closed"></i>
                        </span>
                        <span class="menu-title">Admin/Urun</span>
                    </a>
                </li>
                <li class="nav-item menu-items">
                    <a class="nav-link" asp-area="Admin" asp-controller="Siparis" asp-action="Index">
                        <span class="menu-icon">
                            <i class="mdi mdi-transcribe"></i>
                        </span>
                        <span class="menu-title">Admin/Siparis</span>
                    </a>
                </li>
                <li class="nav-item menu-items">
                    <a class="nav-link" asp-area="Admin" asp-controller="QRKod" asp-action="QRKodOlustur">
                        <span class="menu-icon">
                            <i class="mdi mdi-qrcode-scan"></i>
                        </span>
                        <span class="menu-title">Admin/QR Kod</span>
                    </a>
                </li>
                <li class="nav-item menu-items">
                    <a class="nav-link" asp-area="Admin" asp-controller="Masalar" asp-action="Index">
                        <span class="menu-icon">
                            <i class="mdi mdi-key"></i>
                        </span>
                        <span class="menu-title">Admin/Masalar</span>
                    </a>
                </li>
            </ul>
        </nav>
        <!-- partial -->
        <div class="container-fluid page-body-wrapper">
            <!-- partial:partials/_navbar.html -->
            <nav class="navbar p-0 fixed-top d-flex flex-row">
                <div class="navbar-brand-wrapper d-flex d-lg-none align-items-center justify-content-center">
                    <a class="navbar-brand brand-logo-mini" href="index.html"><img src="~/assets/images/logo-mini.svg" alt="logo" /></a>
                </div>
                <div class="navbar-menu-wrapper flex-grow d-flex align-items-stretch">
                    <button class="navbar-toggler navbar-toggler align-self-center" type="button" data-toggle="minimize">
                        <span class="mdi mdi-menu"></span>
                    </button>
                    <ul class="navbar-nav w-100">
                        <li class="nav-item w-100">
                            <form class="nav-link mt-2 mt-md-0 d-none d-lg-flex search">
                            </form>
                        </li>
                    </ul>
                    <ul class="navbar-nav navbar-nav-right">
                        <li class="nav-item dropdown">
                            <a class="nav-link" id="profileDropdown" href="#" data-bs-toggle="dropdown">
                                <div class="navbar-profile">
                                    <img class="img-xs rounded-circle" src="~/assets/images/faces/face15.jpg" alt="">
                                    <p class="mb-0 d-none d-sm-block navbar-profile-name">@ViewBag.User.UserName</p>
                                    <i class="mdi mdi-menu-down d-none d-sm-block"></i>
                                </div>
                            </a>
                            <div class="dropdown-menu dropdown-menu-right navbar-dropdown preview-list" aria-labelledby="profileDropdown">
                                <h6 class="p-3 mb-0">Profile</h6>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item preview-item" asp-area="Admin" asp-controller="Account" asp-action="Settings">
                                    <div class="preview-thumbnail">
                                        <div class="preview-icon bg-dark rounded-circle">
                                            <i class="mdi mdi-settings text-success"></i>
                                        </div>
                                    </div>
                                    <div class="preview-item-content">
                                            <p class="preview-subject mb-1">Ayarlar</p>
                                    </div>
                                </a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item preview-item" asp-area="Admin" asp-controller="Account" asp-action="LogOut">
                                    <div class="preview-thumbnail">
                                        <div class="preview-icon bg-dark rounded-circle">
                                            <i class="mdi mdi-logout text-danger"></i>
                                        </div>
                                    </div>
                                    <div class="preview-item-content">
                                        <p class="preview-subject mb-1">Çıkış</p>
                                    </div>
                                </a>
                            </div>
                        </li>
                    </ul>
                    <button class="navbar-toggler navbar-toggler-right d-lg-none align-self-center" type="button" data-toggle="offcanvas">
                        <span class="mdi mdi-format-line-spacing"></span>
                    </button>
                </div>
            </nav>
            <!-- partial -->
            <div class="main-panel">
                <div class="content-wrapper">
                    <div class="row">
                        @await Component.InvokeAsync("AylikKar")
                        @await Component.InvokeAsync("GunlukKar")
                    </div>
                    <div class="row ">
                        <div class="col-12 grid-margin">
                            <div class="card">
                                <div class="card-body">
                                    
                                    <div class="table-responsive">
                                        @RenderBody()
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- content-wrapper ends -->
                <!-- partial:partials/_footer.html -->
                <footer class="footer">
                    <div class="d-sm-flex justify-content-center justify-content-sm-between">
                        <span class="text-muted d-block text-center text-sm-left d-sm-inline-block">Copyright © bootstrapdash.com 2021</span>
                        <span class="float-none float-sm-right d-block mt-1 mt-sm-0 text-center"> Free <a href="https://www.bootstrapdash.com/bootstrap-admin-template/" target="_blank">Bootstrap admin template</a> from Bootstrapdash.com</span>
                    </div>
                </footer>
                <!-- partial -->
            </div>
            <!-- main-panel ends -->
        </div>
        <!-- page-body-wrapper ends -->
    </div>
    <!-- container-scroller -->
    <!-- plugins:js -->
    <script src="~/assets/vendors/js/vendor.bundle.base.js"></script>
    <!-- endinject -->
    <!-- Plugin js for this page -->
    <script src="~/assets/vendors/chart.js/Chart.min.js"></script>
    <script src="~/assets/vendors/progressbar.js/progressbar.min.js"></script>
    <script src="~/assets/vendors/jvectormap/jquery-jvectormap.min.js"></script>
    <script src="~/assets/vendors/jvectormap/jquery-jvectormap-world-mill-en.js"></script>
    <script src="~/assets/vendors/owl-carousel-2/owl.carousel.min.js"></script>
    <script src="~/assets/js/jquery.cookie.js" type="text/javascript"></script>
    <!-- End plugin js for this page -->
    <!-- inject:js -->
    <script src="~/assets/js/off-canvas.js"></script>
    <script src="~/assets/js/hoverable-collapse.js"></script>
    <script src="~/assets/js/misc.js"></script>
    <script src="~/assets/js/settings.js"></script>
    <script src="~/assets/js/todolist.js"></script>
    <script src="~/assets/js/qrres.js"></script>
    <!-- endinject -->
    <!-- Custom js for this page -->
    <script src="~/assets/js/dashboard.js"></script>
    <!-- End custom js for this page -->
</body>
@RenderSection("Scripts", required: false)
</html>