RestorantMVC/Controllers/QRController.cs
using DAL.Contexts;
using Entites.Concrate;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.WebUtilities;
using Microsoft.EntityFrameworkCore;
using RestorantMVC.Extensions;

namespace RestorantMVC.Controllers
{
    public class QRController : Controller
    {
        private readonly SqlDbContext dbContext;

        public QRController(SqlDbContext dbContext)
        {
            this.dbContext = dbContext;
        }

        /// <summary>
        /// Eğer bir id içermiyorsa doğrudan Home sayfasına yönlendirir.
        /// </summary>
        public IActionResult Index()
        {
            return RedirectToAction("Scan");
        }

        /// <summary>
        /// ID ile gelen kullanıcıya Cookie yapıştırarak tanınmasını sağlar.
        /// </summary>
        /// <param name="id">MasaID Değeri</param>
        public async Task<IActionResult> Scan(int id , string f)
        {

            //Gelen Firma ID Encrypt'i byte Arraya geri dönüştürülüp string'e çevriliyor.
            byte[] firmaId = WebEncoders.Base64UrlDecode(f);
            string decryptValue = await RestorantExtension.DecryptAsync(firmaId, "DB0C590B-A156-4CE3-BEF8-00B3622B2585");
            this.Response.Cookies.Append("f" , f);

            if (id == null || string.IsNullOrEmpty(id.ToString()) || id == 0)
            {
                return Content("Okuttuğunuz QR Geçersiz veya Zarar görmüş lütfen bir garsondan yardım isteyiniz.");
            }
            else
            {

                // DB'den masa çekiliyor.
                var masa = await dbContext.Masalar.FirmaFilter(decryptValue).Where(p=> p.ID == id).FirstOrDefaultAsync();

                if (string.IsNullOrEmpty(masa.MasaSifresi)) // Masa şifresi var mı diye kontrol edilir.
                {
                    string value = id.ToString();
                    if (Request.Cookies.TryGetValue("MasaId" , out value)) // Kullanıcının Cookie'si var mı diye bakar
                    {
                        return RedirectToAction("Index","Menu", new {area = "Musteri"});
                    }

                    //Cookie eklenir.
                    this.Response.Cookies.Append("MasaId" , id.ToString());
                    
                    //Masa Şifresi oluşturuluyor.
                    dbContext.Masalar.FirmaFilter(decryptValue)
                                     .Where(m => m.ID == id)
                                     .FirstOrDefaultAsync()
                                     .Result.MasaSifresi = masa.SifreOlustur();
                    dbContext.SaveChanges();
                    return RedirectToAction("SifreAyarla", new {firmaId = decryptValue});
                }
                else
                {
                    return RedirectToAction("Giris" , new { id = masa.ID });
                }
            }
        }

        public async Task<IActionResult> SifreAyarla(string firmaId)
        {
            int id = Convert.ToInt32(Request.Cookies["MasaId"]);
            Masa masa = await dbContext.Masalar.FirmaFilter(firmaId).Where(m => m.ID == id).FirstOrDefaultAsync();
            return View(masa);
        }

        [HttpGet]
        public IActionResult Giris(int id)
        {
            ViewBag.Id = id;
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Giris(Masa cloneMasa)
        {
            int id = cloneMasa.ID;
            Masa masa = await dbContext.Masalar.FindAsync(id);

            if (masa == null) { return NotFound(); }

            if (masa.MasaSifresi == cloneMasa.MasaSifresi)
            {
                this.Response.Cookies.Append("MasaId" , id.ToString());

                return RedirectToAction("Index" , "Home");
            }
            else
            {
                return View();
            }
        }
    }
}

RestorantMVC/Views/QR/Giris.cshtml
@model Masa;
@{
    Layout = "~/Views/Shared/_FirmaLayout.cshtml";
}
<body class="align">

    <div class="grid">
<div class="container">
    <form asp-controller="QR" asp-action="Giris" method="post">
        <div class="form-group">
            @Html.HiddenFor(p => p.ID)
            <label for="Sifre">Masa Şifresi</label>
            <input type="text" class="form-control" asp-for="MasaSifresi" placeholder="Masa şifrenizi giriniz">
        </div>

        <button type="submit" class="btn btn-primary">Giriş</button>
    </form>
</div>
    </div>
</body>

RestorantMVC/Views/QR/Scan.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

RestorantMVC/Views/QR/SifreAyarla.cshtml
@model Masa
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<h1>Hoş Geldiniz Masa No'nuz: @Model.MasaID</h1>
<p>Otomatik olarak atanan masa şifreniz: @Model.MasaSifresi</p>