RestorantMVC/Areas/Admin/Controllers/HomeController.cs
using Entites.Concrate;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using RestorantMVC.Extensions;

namespace RestorantMVC.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize]
    public class HomeController : Controller
    {
        private readonly UserManager<Firma> userManager;

        public HomeController(UserManager<Firma> userManager)
        {
            this.userManager = userManager;
        }
        [Authorize]
        public async Task<IActionResult> Index()
        {
            await this.SetUser(userManager);
            return View();
        }
    }
}

RestorantMVC/Areas/Musteri/Controllers/MenuController.cs
using DAL.Contexts;
using Entites.Concrate;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.SignalR;
using Microsoft.AspNetCore.WebUtilities;
using Microsoft.EntityFrameworkCore;
using RestorantMVC.Extensions;
using RestorantMVC.Hubs;

namespace RestorantMVC.Areas.Musteri.Controllers
{
    [Area("Musteri")]
    public class MenuController : Controller
    {
        private readonly SqlDbContext dbContext;
        private readonly IHubContext<SiparisHub> hubContext;
        private string decryptValue;

        public MenuController(SqlDbContext dbContext, IHubContext<SiparisHub> hubContext)
        {
            this.dbContext = dbContext;
            this.hubContext = hubContext;
        }

        public async Task<IActionResult> Index()
        {
            await this.ViewBagSettings(dbContext);

            Request.Cookies.TryGetValue("f" , out decryptValue);
            byte[] bytes = WebEncoders.Base64UrlDecode(decryptValue);
            string firmaId = await RestorantExtension.DecryptAsync(bytes,"DB0C590B-A156-4CE3-BEF8-00B3622B2585");

            Kategori selfIdToId = await dbContext.Kategoriler.FirmaFilter(firmaId).FirstOrDefaultAsync();
            int? findId = selfIdToId.SelfKategoriID;

            return RedirectToAction("Kategori", new {id=findId});
        }

        /// <summary>
        /// Belirli bir kategoriye ait ürünleri listelemek için kullanılan işlem.
        /// </summary>
        /// <param name="id">Kategori kimliği</param>
        public async Task<IActionResult> Kategori(int? id)
        {
            await this.ViewBagSettings(dbContext);

            Request.Cookies.TryGetValue("f" , out decryptValue);
            byte[] bytes = WebEncoders.Base64UrlDecode(decryptValue);
            string firmaId = await RestorantExtension.DecryptAsync(bytes, "DB0C590B-A156-4CE3-BEF8-00B3622B2585");

            Kategori selfIdToId = await dbContext.Kategoriler.FirmaFilter(firmaId).Where(kategori => kategori.SelfKategoriID == id).FirstOrDefaultAsync();
            int findId = selfIdToId.ID;

            var urunler = await dbContext.Urunler.FirmaFilter(firmaId).Where(a => a.KategoriID == findId).ToListAsync();
            return View(urunler);
        }

        /// <summary>
        /// Belirli bir ürünü siparişe eklemek için kullanılan GET işlemi.
        /// </summary>
        /// <param name="id">Eklenen ürünün kimliği</param>
        [HttpGet]
        public async Task<IActionResult> Ekle(int id)
        {
            await this.ViewBagSettings(dbContext);

            Request.Cookies.TryGetValue("f" , out decryptValue);
            byte[] bytes = WebEncoders.Base64UrlDecode(decryptValue);
            string firmaId = await RestorantExtension.DecryptAsync(bytes,"DB0C590B-A156-4CE3-BEF8-00B3622B2585");

            // Cookie'den masa id'sini çekiyorum.
            int masaid = Convert.ToInt32(HttpContext.Request.Cookies["MasaId"]);

            // Ürünü çekiyorum.
            Urun urun = await dbContext.Urunler.FirmaFilter(firmaId).Where(u => u.ID == id).FirstOrDefaultAsync();

            //Siparis Masterler'in listesi
            var siparisMasterler = await dbContext.SiparisMasterlar.FirmaFilter(firmaId).Where(m => m.MasaId == masaid).ToListAsync();

            //Clone sipariş master.
            SiparisMaster clone = null;
            int cloneID = 0;

            foreach (var item in siparisMasterler)
            {
                if (item.IsActive)
                {
                    clone = item;
                    cloneID = item.ID;
                }
            }

            if (clone == null)
            {
                clone = new SiparisMaster();
                clone.IsActive = true;
                clone.FirmaId = firmaId;
                clone.MasaId = masaid;
                await dbContext.SiparisMasterlar.AddAsync(clone);
                await dbContext.SaveChangesAsync();
                cloneID = dbContext.SiparisMasterlar.Count();
            }

            var siparisDetaylar = await dbContext.SiparisDetaylar.FirmaFilter(firmaId)
                                        .Where(v => v.SiparisMasterId == cloneID).ToListAsync();

            clone.SiparisDetay = siparisDetaylar;
            bool urunStatus = true;

            foreach (var item in clone.SiparisDetay)
            {
                if (item.UrunId == urun.ID && item.status == SiparisDetay.Status.Onay_Bekliyor)
                {
                    item.Adet++;
                    item.status = SiparisDetay.Status.Onay_Bekliyor;
                    dbContext.SiparisDetaylar.Update(item);
                    await dbContext.SaveChangesAsync();
                    urunStatus = false;

                    continue;
                }
            }

            if (urunStatus)
            {
                SiparisDetay siparisDetay = new SiparisDetay();
                siparisDetay.FirmaId = firmaId;
                siparisDetay.Adet = 1;
                siparisDetay.Urun = urun;
                siparisDetay.UrunId = urun.ID;
                siparisDetay.CreateTime = DateTime.Now;
                siparisDetay.Fiyat = urun.Fiyat * siparisDetay.Adet;
                siparisDetay.SiparisMasterId = cloneID;
                siparisDetay.status = SiparisDetay.Status.Onay_Bekliyor;
                await dbContext.SiparisDetaylar.AddAsync(siparisDetay);
                await dbContext.SaveChangesAsync();
            }
            await hubContext.Clients.All.SendAsync("YeniSiparisGeldi", 1);

            return RedirectToAction("Index" , "Siparis");
        }

        /// <summary>
        /// Belirli bir ürünü siparişe eklemek için kullanılan POST işlemi.
        /// </summary>
        /// <param name="siparisMaster">Sipariş Master nesnesi</param>
        [HttpPost]
        public async Task<IActionResult> Ekle(SiparisMaster siparisMaster)
        {
            await this.ViewBagSettings(dbContext);

            return View();
        }
    }
}

RestorantMVC/Controllers/FirmaLoginController.cs
using AutoMapper;
using Entites.Concrate;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using RestorantMVC.Models;
using System.Text;
using static System.Runtime.InteropServices.JavaScript.JSType;

namespace RestorantMVC.Controllers
{
    public class FirmaLoginController : Controller
    {
        private readonly UserManager<Firma> userManager;
        private readonly IMapper mapper;
        private readonly SignInManager<Firma> signInManager;

        public FirmaLoginController(UserManager<Firma> userManager, IMapper mapper, SignInManager<Firma> _signInManager)
        {
            this.userManager = userManager;
            this.mapper = mapper;
            signInManager = _signInManager;
        }
        public IActionResult Index()
        {
            return RedirectToAction("Login");
        }

        public async Task<IActionResult> Login()
        {
            LoginDto loginDto = new LoginDto();
            return View(loginDto);
        }


        [HttpPost]
        public async Task<IActionResult> Login(LoginDto loginDto)
        {

            //Validasyondan geçmedi ise ayni verileri view'e geri gonder
            if (!ModelState.IsValid)
            {
                return View(loginDto);
            }
            else
            {

                var  user = await userManager.FindByEmailAsync(loginDto.Email);


                if (user == null)
                {
                    ModelState.AddModelError("" , "Boyle bir kullanici Yoktur");
                    return View(loginDto);
                }

                // Burasi Mail onaylanmi mi ona bakar
                if (!await userManager.IsEmailConfirmedAsync(user))
                {
                    ModelState.AddModelError("" , "Mail onaylanmamistir");
                    return View(loginDto);
                }

                //signInManager verilen password ile oturum Acar
                await signInManager.SignOutAsync();
                var result = await signInManager.PasswordSignInAsync(user,loginDto.Password,loginDto.RememberMe,true);
                if (result.Succeeded)
                {
                    return RedirectToAction("Index" , "Home" , new { Area = "Admin" });
                }

                ModelState.AddModelError("" , "Email yada Sifre Hatalidir");
                return View(loginDto);
            }


            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> Register()
        {
            FirmaRegisterDTO firma = new ();
            return View(firma);
        }
        [HttpPost]
        public async Task<IActionResult> Register(FirmaRegisterDTO firmadto)
        {

            var firma = mapper.Map<Firma>(firmadto);

            if(!ModelState.IsValid) 
            { 
                return View(firmadto);
            }
            var result = await userManager.CreateAsync(firma,firmadto.Password);

            if (result.Succeeded)
            {

                var code = await userManager.GenerateEmailConfirmationTokenAsync(firma);

                StringBuilder message = new StringBuilder();
                message.AppendLine("<html>");
                message.AppendLine("<Head>");
                message.AppendLine("<meta charset='UTF-8' />");

                message.AppendLine("</Head>");
                message.AppendLine("<body>");

                message.AppendLine($"<p> Merhaba {firma.UserName}  </p> <br>");

                message.AppendLine("<p> Uyelik islemlerini tamamlamak icin asagidaki linki tiklayin </p>");

                string host = HttpContext.Request.Scheme + "://" + HttpContext.Request.Host.Value + "/ConfirmEmail?uid=";
                message.AppendLine($"<a href='{host}{firma.Id}&code={code}'> Onaylayin </a>");


                message.AppendLine("</body>");


                message.AppendLine("</html>");

                EmailHelper email = new EmailHelper();

                bool sonuc = email.SendEmail(firma.Email, message.ToString());

                if (sonuc)
                {
                    return RedirectToAction("Index" , "Home");

                }
                else
                {
                    ModelState.AddModelError("" , "Mail Goderiminde hata olustu");
                    return View(firmadto);
                }

            }
            else
            {
                var error = result.Errors.FirstOrDefault();
                ModelState.AddModelError("Sorunla karşılaşıldı" , error.Description);
                return View(firmadto);
            }
        }
        public async Task<IActionResult> Logout()
        {
            await signInManager.SignOutAsync();
            return RedirectToAction("Index" , "Home");
        }

        [Route("ConfirmEmail")]
        public async Task<IActionResult> ConfirmEmail(string uid , string code)
        {

            ConfirmEmailModel model = new();
            if (!string.IsNullOrEmpty(uid) && !string.IsNullOrEmpty(code))
            {
                var user = await userManager.FindByIdAsync(uid);
                code = code.Replace(' ' , '+');
                model.Email = user.Email;
                var result = await userManager.ConfirmEmailAsync(user, code);

                if (result.Succeeded)
                {
                    return View(model);
                }
                else
                {
                    var error = result.Errors.FirstOrDefault();
                    model.ErrorDescription = error.Description;
                    model.HasError = true;
                    ModelState.AddModelError("" , error.Description);
                    return View(model);
                }
            }
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> ConfirmEmail(ConfirmEmailModel model)
        {
            return View(model);
        }
    }
}

RestorantMVC/Controllers/HomeController.cs
using DAL.Contexts;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using RestorantMVC.Models;
using System.Diagnostics;

namespace RestorantMVC.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly SqlDbContext dbContext;

        public HomeController(ILogger<HomeController> logger , SqlDbContext dbContext)
        {
            _logger = logger;
            this.dbContext = dbContext;
        }

        public async Task<IActionResult> Index()
        {
            var viewModel = new LayoutViewModel { Kategoriler = dbContext.Kategoriler.ToList() };
            int entityID = Convert.ToInt32(HttpContext.Request.Cookies["MasaId"]);
            if (entityID == null || entityID == 0)
            {
                return RedirectToAction("Landing", "Home");
            }
                var masaID = await dbContext.Masalar.FindAsync(entityID);
                ViewBag.MasaID = masaID.MasaID;
            


            return View(viewModel);
        }

        public IActionResult Landing()
        {
            return View();
        }

        public async Task<IActionResult> Menu(int? id)
        {
            var urunler =  await dbContext.Urunler.Where(a => a.KategoriID == id).ToListAsync();

            return View(urunler);
        }

        [ResponseCache(Duration = 0 , Location = ResponseCacheLocation.None , NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

RestorantMVC/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
    Masa masa = new();
}

<div class="text-center">
    <h1 class="display-4">Hoşgeldiniz</h1>
    <h1 class="display-4" id="Musteri">Masa Numaranız : @ViewBag.MasaID</h1>
    <a class="btn btn-danger btn-lg" asp-area="Musteri" asp-controller="Menu" asp-action="Kategori" asp-route-id="1">MENU</a>
</div>

RestorantMVC/Views/Home/Landing.cshtml
@{
    ViewData["Title"] = "IndexHome Page";
    Masa masa = new();
    Layout = "~/Views/Shared/_LandingLayout.cshtml";
}



<body>

    <!-- ***** Preloader Start ***** -->
    <div id="preloader">
        <div class="jumper">
            <div></div>
            <div></div>
            <div></div>
        </div>
    </div>
    <!-- ***** Preloader End ***** -->
    <!-- ***** Header Area Start ***** -->
    <header class="header-area header-sticky">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <nav class="main-nav">
                        <!-- ***** Logo Start ***** -->
                        <a href="#" class="logo">QRestoran</a>
                        <!-- ***** Logo End ***** -->
                        <!-- ***** Menu Start ***** -->
                        <ul class="nav">
                            <li class="scroll-to-section"><a asp-controller="FirmaLogin" asp-action="Login" class="active">Giriş</a></li>
                            <li class="scroll-to-section"><a asp-controller="FirmaLogin" asp-action="Register" class="active">Kayıt Ol</a></li>
                        </ul>
                        <!-- ***** Menu End ***** -->
                    </nav>
                </div>
            </div>
        </div>
    </header>
    <!-- ***** Header Area End ***** -->
    <!-- ***** Welcome Area Start ***** -->
    <div class="welcome-area" id="welcome">

        <!-- ***** Header Text Start ***** -->
        <div class="header-text">
            <div class="container">
                <div class="row">
                    <div class="left-text col-lg-6 col-md-6 col-sm-12 col-xs-12" data-scroll-reveal="enter left move 30px over 0.6s after 0.4s">
                        <h1>QRestoran Ücretsizdir <strong>Sizin İçin</strong></h1>
                        <p>Restoran deneyiminizi daha modern, hızlı ve güvenli hale getirmek için QR Menü Sistemimizi kullanın. Yemek seçiminizi anında yapın ve lezzet dolu bir deneyime adım atın!</p>
                        <a asp-controller="FirmaLogin" asp-action="Register" class="main-button-slider">Hemen Kayıt Ol!</a>
                    </div>
                    <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12" data-scroll-reveal="enter right move 30px over 0.6s after 0.4s">
                        <img src="~/assets/images/slider-icon.png" class="rounded img-fluid d-block mx-auto" alt="First Vector Graphic">
                    </div>
                </div>
            </div>
        </div>
        <!-- ***** Header Text End ***** -->
    </div>
    <!-- ***** Welcome Area End ***** -->
    <!-- ***** Features Big Item Start ***** -->
    <section class="section" id="about">
        <div class="container">
            <div class="row">
                <div class="col-lg-7 col-md-12 col-sm-12" data-scroll-reveal="enter left move 30px over 0.6s after 0.4s">
                    <img src="~/assets/images/left-image.png" class="rounded img-fluid d-block mx-auto" alt="App">
                </div>
                <div class="right-text col-lg-5 col-md-12 col-sm-12 mobile-top-fix">
                    <div class="left-heading">
                        <h5>QR Menü Sistemi: Yemeklerinizi Hızlı ve Kolayca Keşfedin!</h5>
                    </div>
                    <div class="left-text">
                        <p>
                            Geleneksel menüleri bir kenara bırakın ve yemek seçimlerinizi daha hızlı ve etkileşimli bir şekilde yapın! QR Menü Sistemimiz, restoran deneyiminizi daha modern ve kullanıcı dostu hale getiriyor.

                        </p>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-12">
                    <div class="hr"></div>
                </div>
            </div>
        </div>
    </section>
    <!-- ***** Features Big Item End ***** -->
    <!-- ***** Features Big Item Start ***** -->
    <section class="section" id="about2">
        <div class="container">
            <div class="row">
                <div class="left-text col-lg-5 col-md-12 col-sm-12 mobile-bottom-fix">
                    <div class="left-heading">
                        <h5>Hemen Başlayalım !</h5>
                    </div>
                    <ul>
                        <li>
                            <img src="~/assets/images/about-icon-01.png" alt="">
                            <div class="text">
                                <h6>QR Kodunu Tara !</h6>
                                <p>Masanıza yerleştirilmiş olan QR kodunu telefonunuzun kamerasıyla tarayın.</p>
                            </div>
                        </li>
                        <li>
                            <img src="~/assets/images/about-icon-02.png" alt="">
                            <div class="text">
                                <h6>Menüyü Keşfedin !</h6>
                                <p>Anında restoran menümüze ulaşın ve geniş yelpazede sunulan yemekleri inceleyin.</p>
                            </div>
                        </li>
                        <li>
                            <img src="~/assets/images/about-icon-03.png" alt="">
                            <div class="text">
                                <h6>Siparişinizi Verin !</h6>
                                <p>Beğendiğiniz yemekleri seçin, özel isteklerinizi ekleyin ve siparişinizi kolayca tamamlayın.</p>
                            </div>
                        </li>
                    </ul>
                </div>
                <div class="right-image col-lg-7 col-md-12 col-sm-12 mobile-bottom-fix-big" data-scroll-reveal="enter right move 30px over 0.6s after 0.4s">
                    <img src="~/assets/images/right-image.png" class="rounded img-fluid d-block mx-auto" alt="App">
                </div>
            </div>
        </div>
    </section>
    <!-- ***** Features Big Item End ***** -->
    <!-- ***** Features Small Start ***** -->
    <section class="section" id="services">
        <div class="container">
            <div class="row">
                <div class="owl-carousel owl-theme">
                    <div class="item service-item">
                        <div class="icon">
                            <i><img src="~/assets/images/service-icon-01.png" alt=""></i>
                        </div>
                        <h5 class="service-title">Tek Tıkla Menü Oluşturma</h5>
                        <p>Artık restoranınızın menüsünü oluşturmak ve güncellemek sadece bir tık uzağınızda! Yenilikçi "Tek Tıkla Menü Oluşturma" özelliğiyle restoran işinizi kolaylaştırın.</p>
                        
                    </div>
                    <div class="item service-item">
                        <div class="icon">
                            <i><img src="~/assets/images/service-icon-02.png" alt=""></i>
                        </div>
                        <h5 class="service-title">Tek Tıkla QR Oluşturma: Hızlı, Basit ve Etkili!</h5>
                        <p>Artık QR kodlarınızı oluşturmak sadece bir tık uzağınızda! Yenilikçi "Tek Tıkla QR Oluşturma" özelliğiyle işinizi kolaylaştırın. </p>
                        
                    </div>
                    <div class="item service-item">
                        <div class="icon">
                            <i><img src="~/assets/images/service-icon-03.png" alt=""></i>
                        </div>
                        <h5 class="service-title">Anında Ürün Ekleme ve Düzenleme: Enflasyona Ayak Uydurun!</h5>
                        <p>İşlerinizi kolaylaştırmak ve müşterilerinizle daha hızlı etkileşimde bulunmak için burada. Yepyeni "Anında Ürün Ekleme ve Düzenleme" özelliği ile işiniz artık parmaklarınızın ucunda.</p>
                        
                    </div>
                    <div class="item service-item">
                        <div class="icon">
                            <i><img src="~/assets/images/service-icon-02.png" alt=""></i>
                        </div>
                        <h5 class="service-title">Sipariş Görüntüleme ve Kontrol Etme: İşinizi Kontrol Altında Tutun!</h5>
                        <p>İşletmenizin sipariş yönetimini bir üst seviyeye taşımak ve müşteri deneyimini en üst düzeye çıkarmak artık daha kolay! "Siparişleri Görüntüleme ve Kontrol Etme" özelliği ile işlemlerinizi yönetmek hiç bu kadar hızlı olmamıştı.</p>
                        
                    </div>
                    <div class="item service-item">
                        <div class="icon">
                            <i><img src="~/assets/images/service-icon-01.png" alt=""></i>
                        </div>
                        <h5 class="service-title">Aylık Brüt Kar İstatistiği: İşletmenizin Performansını Anında Analiz Edin!</h5>
                        <p>İşletmenizin mali performansını anlık olarak takip edebilmenin kolay bir yolu artık burada! Yepyeni "Aylık Brüt Kar İstatistiği" özelliği ile işletmenizin finansal sağlığını görsel ve anlaşılır bir şekilde analiz edin.</p>
                        
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- ***** Features Small End ***** -->
    <!-- ***** Footer Start ***** -->
    <footer>
        <div class="container">
            <div class="row">
                <div class="col-lg-7 col-md-12 col-sm-12">
                    <p class="copyright">
                        Copyright &copy; 2023 QRESTORAN
                    </p>
                </div>
            </div>
        </div>
    </footer>

    <!-- jQuery -->
    <script src="~/assets/js/jquery-2.1.0.min.js"></script>

    <!-- Bootstrap -->
    <script src="~/assets/js/popper.js"></script>
    <script src="~/assets/js/bootstrap.min.js"></script>

    <!-- Plugins -->
    <script src="~/assets/js/owl-carousel.js"></script>
    <script src="~/assets/js/scrollreveal.min.js"></script>
    <script src="~/assets/js/waypoints.min.js"></script>
    <script src="~/assets/js/jquery.counterup.min.js"></script>
    <script src="~/assets/js/imgfix.min.js"></script>

    <!-- Global Init -->
    <script src="~/assets/js/custom.js"></script>

</body>

RestorantMVC/Views/Home/Menu.cshtml
@model ICollection<Urun>
@inject IHttpContextAccessor httpContextaccessor

@{
    ViewData["Title"] = "Menu";
}

<h1>Menu</h1>

<div class="container">
    <div class="row">
        @foreach (var item in Model)
        {
            <div class="col-sm">
                @if(string.IsNullOrEmpty(item.FotografLink))
                {       
                    <div class="col-4">
                        <div class="card" style="width: 18rem;">
                            <div class="card-body">
                                <h5 class="card-title">@item.UrunAdi</h5>
                                <h6 class="card-subtitle mb-2">Fiyat: @item.Fiyat</h6>
                                <p class="card-text">@item.UrunAciklama</p>
                                <a class="card-link btn btn-outline-secondary" asp-route-id="@item.ID">Sepete Ekle</a>
                            </div>   
                        </div>
                    </div>
                }
                else
                {
                    <div class="card" style="width: 18rem;">
                        <img class="card-img-top" src="@item.FotografLink" alt="Card image cap">
                        <div class="card-body">
                            <h5 class="card-title">@item.UrunAdi</h5>
                            <h6 class="card-subtitle mb-2">Fiyat: @item.Fiyat</h6>
                            <p class="card-text">@item.UrunAciklama</p>
                            <a class="card-link btn btn-outline-secondary" asp-route-id="@item.ID">Sepete Ekle</a>
                        </div>
                    </div>
                }
            </div>

        }
    </div>
</div>